### ISSUE TITLE
phusion update?

### ISSUE THREAD

**Issue by kjake** [dlandon/baseimage#3]
phusion 0.10.0 is based on Ubuntu 16.04 and while it is LTS and working fine, my reason for asking is selfish; I'd like to try using GPU accelerated hardware transcoding in Zoneminder, but I have previous experiences with doing this in Docker and using the VAAPI / Intel chipset and it frankly will not function in Ubuntu 16.04, but works beautifully in 18.04.  I suspect that the drivers and/or runtime is older in 16.04 and haven't been back-ported, but have not confirmed this assumption.

phusion has released 0.10.1, 0.10.2, and 0.11 and it has been updated to be based on Ubuntu 18.04.  It would be nice to have this update at the base level of your containers, but I understand that it will take testing.

If this isn't something that you can do, I understand and am happy to fork things for my own purposes.

Thanks!

**Comment by dlandon** [comment]
It is on my list of things to do.  I will try it this weekend and see what issues come up.

**Comment by dlandon** [comment]
I've updated the zoneminder-master (1.33) Docker to Phusion 11.0.  The stable zoneminder (1.32) has issues and will stay at 10.0.2.
